// <auto-generated />
namespace Pharmacy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sp_Creates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sp_Creates));
        
        string IMigrationMetadata.Id
        {
            get { return "202006281808046_Sp_Creates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
