// <auto-generated />
namespace Pharmacy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sp_Bookings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp_Bookings));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191501100_sp_Bookings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
